global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: unarxiv-httpapi
    static_configs:
      - targets: ['httpapi:8080']
  - job_name: unarxiv-crawler
    static_configs:
      - targets: ['crawler:8090']
